import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

// Custom Directives used in this screen
// 1) InputRuleDirective     → formats input in real-time (digits-only / uppercase)
// 2) RequiredErrorDirective → applies error UI only when (requiredField && showError) is true
import { InputRuleDirective } from './directives/input-rule';
import { RequiredErrorDirective } from './directives/required-error';

// Allowed status values for each submitted KYC record
// Using a union type prevents invalid values like 'Done' or 'Approved' by mistake.
type KycStatus = 'Pending' | 'Verified';

// Data structure of one submitted KYC application
// This is what we store in memory and show on the dashboard list.
interface KycApplication {
  id: number;        // unique identifier (simulating backend-generated ID)
  fullName: string;  // applicant full name
  mobile: string;    // 10-digit mobile number
  pan: string;       // 10-character PAN
  email: string;     // applicant email id
  status: KycStatus; // current processing status
}

@Component({
  selector: 'app-root',

  // Standalone Component imports
  // Anything used in the HTML template must be imported here.
  //
  // - FormsModule         → enables template-driven forms features like [(ngModel)]
  // - InputRuleDirective  → used as an attribute directive on input fields
  // - RequiredErrorDirective → used to show required-field styling after submit attempt
  imports: [
    InputRuleDirective,
    RequiredErrorDirective,
    FormsModule,
  ],

  // External template file (clean separation of TS + HTML)
  templateUrl: './app.html'
})
export class App {

  // FORM MODEL (Template-driven form values)
  // These are bound to the input fields using [(ngModel)].
  // They always contain the latest values typed by the user.
  fullName = '';
  mobile = '';
  pan = '';
  email = '';

  // UI STATE (Controls when validation errors are shown)
  // We keep it false initially so the form looks clean on first load.
  // We set it true only when user clicks Submit.
  // Template uses this to show:
  // - validation messages
  // - RequiredErrorDirective styling
  isSubmitted = false;

  // IN-MEMORY STORAGE (Demo Purpose)
  // In real applications, IDs are generated by the backend database.
  // Here we simulate that using an auto-increment variable.
  private nextId = 1001;

  // Stores all submitted applications in memory.
  // This list is shown in the dashboard on the right side.
  applications: KycApplication[] = [];

  // VALIDATION GETTERS (Readable + reusable rules)
  // These getters keep the submit() method simple.
  // Also, the template can directly use these flags for UI messages.

  // Full Name must not be empty
  get isFullNameInvalid(): boolean {
    // trim() removes leading/trailing spaces so "   " is treated as empty
    return this.fullName.trim().length === 0;
  }

  // Mobile must be exactly 10 digits
  // Note: InputRuleDirective (digits rule) already removes non-digits.
  get isMobileInvalid(): boolean {
    return this.mobile.trim().length !== 10;
  }

  // PAN must be exactly 10 characters
  // Note: InputRuleDirective (uppercase rule) already converts to uppercase.
  get isPanInvalid(): boolean {
    return this.pan.trim().length !== 10;
  }

  // Basic email format validation
  // This checks: something@something.something
  get isEmailInvalid(): boolean {
    return !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.email.trim());
  }

  // Single “master” check for overall form validity
  // If any field fails, the form is invalid.
  get isFormInvalid(): boolean {
    return (
      this.isFullNameInvalid ||
      this.isMobileInvalid ||
      this.isPanInvalid ||
      this.isEmailInvalid
    );
  }

  // SUBMIT HANDLER
  submit(): void {

    // Step 1: Mark as submitted
    // This activates required-field styling + validation messages in the UI.
    this.isSubmitted = true;

    // Step 2: Stop if validation fails
    // We don't store anything until the form is valid.
    if (this.isFormInvalid) return;

    // Step 3: Build the record that will be shown in the dashboard list
    // trim() ensures stored values are clean and consistent.
    const newApp: KycApplication = {
      id: this.nextId++,              // simulate auto-generated unique ID
      fullName: this.fullName.trim(), // clean full name
      mobile: this.mobile.trim(),     // clean mobile
      pan: this.pan.trim(),           // clean PAN
      email: this.email.trim(),       // clean email
      status: 'Pending'               // default status for newly created record
    };

    // Step 4: Add the latest record at the TOP of the list
    // This is common in dashboards (most recent entry first).
    this.applications = [newApp, ...this.applications];

    // Step 5: Reset fields for next entry
    // Makes the form ready for a new submission.
    this.fullName = '';
    this.mobile = '';
    this.pan = '';
    this.email = '';

    // Step 6: Reset submission state
    // This removes validation UI and makes the next form entry clean.
     this.isSubmitted = false;
  }

  // RESET HANDLER
  reset(): void {
    // Clear all input fields
    this.fullName = '';
    this.mobile = '';
    this.pan = '';
    this.email = '';

    // Reset validation UI state (hide errors / remove red highlight)
    this.isSubmitted = false;
  }
}